### ISSUE TITLE
CRD Code Context root issue

### ISSUE THREAD

**Issue by AjeeshPillai** [HL7-DaVinci/CRD#107]
We are trying to configure CRD app into JBoss Server, Our admin team is looking for the context root value to configure.

Currently the application is running with the URL : http://davincipoc01:80/
We like to setup the root context so that the application can run on the following url :
http://davincipoc01:80/davincicrd

Also please let us know is any alternative configuration within the code to resolve this issue.

**Comment by KeeyanGhoreshi** [comment]
You can change the context path by changing the `contextPath` parameter in the `application.yml` file located [here](https://github.com/HL7-DaVinci/CRD/blob/master/server/src/main/resources/application.yml).  Make sure your version of the app is current as the ability to change the context path is a newer feature.
