### ISSUE TITLE
Containerization/HL7 Marketplace packaging.

### ISSUE THREAD

**Issue by preston** [HL7-DaVinci/CRD#116]
Hi, I'm with VA and HSPC and there are some current talks going on about running this at HSPC. Could we get a Docker-based build with some instructions on the appropriate env vars that need to be injected? We will be using Keycloak as the SSO IDP.

**Comment by preston** [comment]
I don't fully understand how this works and haven't looked at how all the configuration is read, but I suspect this would require changing the use of the application.yml file to read more technology-agnostic environment variables at startup, as opposed to baking in any type of configuration into the build. https://github.com/HL7-DaVinci/CRD/blob/master/server/src/main/resources/application.yml
CC @neuronsong

**Comment by daco101** [comment]
Hi Preston, thanks for reaching out. We now have a docker deployment process set up, currently the relevant changes are in the "deploy" branch. We are using jib to create the docker image. In terms of what needs to be deployed now, I think its just the main java application. The readme has information about using keycloak and such, but that's to simulate requests from an EHR.
The deploy process right now basically looks like `gradle jib` and `docker run -e SPRING_PROFILES_ACTIVE='localDb'  -e LOCALDBRULES='/rules/'  -p 8090:8090 --name crd-server -d davincicrd/crd-server`. We use spring boot, which will automatically use configs from the environment rather than the application.yml.

**Comment by preston** [comment]
@daco101 Ok. The Keycloak part is a requirement for us so we'll definitely need more details fairly soon. It wasn't immediately obvious to me what all the config env vars can be set, so I just wanted to bring it up early! I think @neuronsong, @nschwertner and I are going to meet sometime next week to get on the same page with what all this does, how it works etc.

In case it matters, the target environment will be run out of AWS us-east-1a (Virginia). The current (empty) sandbox server is at https://davinci.hspconsortium.org and will be managed via external tools on another host. Our databases are _not_ containerized by design, so the assumption is that any database connection string will be provider by env var URI, e.g.

```WHATEVER_DATABASE_URL=postgres://username:password@db.example.com:5432/schema_name```

Databases are not directly internet accessible, so if you have a need to connect directly at some point just know it will probably require some additional manual intervention.

Also know that, per the Marketplace specification, all certificate management and SSL crypto is handled *outside* the container. We can set HTTP headers at the reverse proxy if needed so you know it was used and know what base URL you are running under, but other than that you shouldn't have to worry about SSL/TLS.

**Comment by preston** [comment]
Self-reminder to ask about the "in-memory database". To be run clustered elastically there can't really be any cache coherency issues, sticky sessions etc. We do have Redis too if you need something in memory but don't have a way to sync multiple instances.

**Comment by daco101** [comment]
We've published an image to docker hub, so you should be able to get our basic server up and running with the following:
`docker pull davincicrd/crd-server:latest`
```bash
docker run \
  -e SPRING_PROFILES_ACTIVE='localDb' \
  -e LOCALDBRULES='/rules/' \
  -p 8090:8090 \
  --name crd-server \
  -d davincicrd/crd-server```

**Comment by neuronsong** [comment]
Hey guys. Sorry I'm late to the party on this thread. My github notifications were getting squirreled away and buried. Is the docker setup working? Has the in-memory db question been answered for multiple instances?

**Comment by preston** [comment]
@neuronsong @daco101 Yes and I think yes. A baseline “davinci-crd” continuous delivery pipeline is now wired up. I’ve tested it a few times, but also haven’t tried pushing any updated builds. Live CRD sandbox URL:

	https://davinci-crd.hspconsortium.org

The way the autodeployment works is that any “hspc/davinci-crd:latest” image pushed to Docker Hub (https://cloud.docker.com/u/hspc/repository/docker/hspc/davinci-crd) fires a Webhook to the HSPC Portainer management service. (Pushing to davincicrd/crd-server will NOT trigger anything.) You can emulate this manually by:

	curl -X POST https://portainer.hspconsortium.org/api/webhooks/a2cd72c7-db22-4b4f-affc-39370de4d563

When received, Portainer has the :latest version of the image downloaded the davinci server and deploys it in a rolling fashion at a 15s delay between tasks. There are no less than 2 running at any given time, so during the <1m it takes to do this and start the internal Spring apps you’ll get a mix of old/new instances responding to requests. If you’d like the ability to get service logs I can grant access to the Portainer UI for you.

This all needs documentation, but other than that, seems legit!

Preston

**Comment by preston** [comment]
Also please make sure there are no disk writes going on -- it seems like spring may be logging somewhere but I'm not sure. Just write to stdout if you want them.

**Comment by preston** [comment]
@daco101 I'd like to change this to auto deploy master similar to other repositories being set up for deployment. Could the Dockerfile and necessary changes please be merged in to master?

**Comment by preston** [comment]
Could someone please merge the Dockerfile (and anything else needed) into master? This is preventing HSPC autodeployment from working and I'll be gone for the week pretty soon!

**Comment by plarocque4** [comment]
A Dockerfile has been added and merged into master.
