### ISSUE TITLE
Need architecture and deployment diagram(s)

### ISSUE THREAD

**Issue by preston** [HL7-DaVinci/CRD#118]
I'm a little confused on the overall architecture of how DaVinci operates. Could we get some quick drawings on how things fit together? There are 8 public repos and it's hard to tell what's going on from the surface.

**Comment by daco101** [comment]
I believe this has been discussed elsewhere - our understanding is that currently the separate davinci use cases are distinct code bases with distinct deployments.

**Comment by preston** [comment]
Will create a wiki page as HSPC for this type of thing.

**Comment by preston** [comment]
https://healthservices.atlassian.net/wiki/spaces/DAVINCI/overview
