### ISSUE TITLE
Please add me as GitHub org collaborator. 

### ISSUE THREAD

**Issue by preston** [HL7-DaVinci/CRD#119]
I'm configuring HSPC resources and need to set up web hooks for continuous deployment. Sounds like the same process will apply for most of the repos in this GitHub organization. (Username is @preston) @neuronsong may or may not need access as well. Thanks!

**Comment by daco101** [comment]
You should have access now.

**Comment by preston** [comment]
@daco101 I do for this one now, but need access to either all repos being deployed or access at the org (as opposed to repo) level.

**Comment by daco101** [comment]
I believe @VietDNguyen is responsible for the org level access.

**Comment by preston** [comment]
@VietDNguyen Could you add me to the team at the org level? I need to configure hooks for the delivery pipeline.

**Comment by KeeyanGhoreshi** [comment]
Has this issue been closed? Or do you still need access at the org level?

**Comment by preston** [comment]
Yup I think I'm good, thanks.
