### ISSUE TITLE
Minor confusion over supported gradle

### ISSUE THREAD

**Issue by MegRiley** [HL7-DaVinci/CRD#195]
I've been trying to configure the CRD/DTR environment but I'm seeing conflicting information about which version of gradle is required to build and run it. The github readme says :"is built with Gradle 4.9" however the confluence page references needing version 6.3 of gradle.  Which page is correct or are both supported?

**Comment by lpdecelles** [comment]
@MegRiley thanks for the question. I think the Confluence page you are referring to, is for internal use only. Is that correct? Either way these have been updated to be more consistent.

**Comment by MegRiley** [comment]
I believe it maybe internal use only since I came across it when trying to correct certificate issues I was having. Thanks for making the two consistent. (I believe the confluence page was intended to help onboard new people)

**Comment by FrancisChristy** [comment]
I also face issue with this gradle version in IntelliJ. I have gradle 6.7 in my system and jdk 11.0.8. I'am getting an error that "JDK 11.0.8 isn't compatible with gradle 4.8". How can I change the gradle version to 6.7?
<img width="935" alt="Capture" src="https://user-images.githubusercontent.com/58290900/103733881-ba495900-5010-11eb-976f-2d74a794ecee.PNG">
